### ISSUE TITLE
Fabric Manager will not run on systems in FIPS mode

### ISSUE THREAD

**Issue by rixon** [cornelisnetworks/opa-fm#15]
When running a system in FIPS mode (kernel parameter fips=1), Fabric Manager fails to start.  This appears to be caused by FIPS using MD5 hashes.  MD5 is not a validated algorithm under FIPS, so the library function calls fail, causing FM to fail.

`[root@localhost ~]# systemctl status opafm
● opafm.service - OPA Fabric Manager
   Loaded: loaded (/usr/lib/systemd/system/opafm.service; disabled; vendor preset: disabled)
   Active: failed (Result: signal) since Fri 2019-03-29 17:44:22 EDT; 2 days ago
  Process: 31401 ExecStop=/usr/lib/opa-fm/bin/opafmd halt (code=exited, status=0/SUCCESS)
  Process: 31398 ExecStart=/usr/lib/opa-fm/bin/opafmd -D (code=exited, status=0/SUCCESS)
 Main PID: 31399 (code=killed, signal=ABRT)

Mar 29 17:44:22 localhost.localdomain systemd[1]: Starting OPA Fabric Manager...
Mar 29 17:44:22 localhost.localdomain systemd[1]: Started OPA Fabric Manager.
Mar 29 17:44:22 localhost.localdomain opafmd[31398]: md5_dgst.c(82): OpenSSL internal error, assertion failed: Digest MD5 forbidden in FIPS mode!
Mar 29 17:44:22 localhost.localdomain systemd[1]: opafm.service: main process exited, code=killed, status=6/ABRT
Mar 29 17:44:22 localhost.localdomain systemd[1]: Unit opafm.service entered failed state.
Mar 29 17:44:22 localhost.localdomain systemd[1]: opafm.service failed.`

Steps to reproduce: 

1. Boot system to FIPS mode by adding `fips=1` to kernel command line.
2. Try starting opa-fm.  It will fail to start as listed in error text above.

**Comment by sjb017** [comment]
Hello Paul,

Thank you for this request. We are evaluating the requirement and will likely include a fix in our next push.

Scott Breyer
Intel Corporation
Maintainer, intel/opa-fm

**Comment by ddalessa** [comment]
Checked with the internal development team and this is no longer an issue.
