### ISSUE TITLE
undefined macro 'NL' in manpages

### ISSUE THREAD

**Issue by ghost** [cornelisnetworks/opa-fm#17]
These undefined macros should be removed.

opa-fm]$ git grep -E  '\.NL'
Esm/ib/man/opafmcmd.manPage:.NL
Esm/ib/man/opafmcmd.manPage:.NL
Esm/ib/man/opafmcmd.manPage:.NL
Esm/ib/man/opafmcmd.manPage:.NL
Esm/ib/man/opafmcmd.manPage:.NL
Esm/ib/man/opafmcmd.manPage:.NL
Esm/ib/man/opafmcmd.manPage:.NL
Esm/ib/man/opafmcmdall.manPage:.NL
Esm/ib/man/opafmcmdall.manPage:.NL
Esm/ib/man/opafmcmdall.manPage:.NL
Esm/ib/man/opafmcmdall.manPage:.NL
Esm/ib/man/opafmcmdall.manPage:.NL
Esm/ib/man/opafmcmdall.manPage:.NL
Esm/ib/man/opafmcmdall.manPage:.NL

**Comment by ddalessa** [comment]
Dead account filed 5+ years ago. Tossing out of the boat.
