### ISSUE TITLE
Do you need OPA specific builds of MPI libraries?

### ISSUE THREAD

**Issue by JohnWestlund** [cornelisnetworks/opa-fm#2]
I see the `opa-fm` code includes scripts to build `openmpi` and `mvapich2`. Two questions:
1. Why does the FM need to be building these libraries? They're not actually dependencies of the FM are they?
2. Is there something special about these builds? That is to say, can I just use standard builds of `openmpi` and `mvapich2` (and `impi`?) and have all the expected functionality/features/performance without having OPA specific builds? will it work but have reduced performance? am I totally out of luck without these specific builds?

**Comment by sjb017** [comment]
Hi John,

Those scripts came along with the CommonInstall directory, which is present in several of our repositories as shared code. The MPI scripts are not used in the FM build. The FM build will not affect your MPI packages.

Scott Breyer
Maintainer, 01org/opa-fm

**Comment by JohnWestlund** [comment]
That's good to hear. But I do see that these build scripts make different build decision when built for different targets ("-O build the MPI targeted for the Omnipath HFI PSM API"). What do I lose if I try and use a recent but existing MPI build targeted for IB?  I assume an `MVAPICH2` built for verbs would be a problem, but what IMPI, OpenMPI, etc?

**Comment by mwheinz** [comment]
I'm not entirely sure what you're asking. The purpose of these scripts is to simplify building your own MPI binaries and, in particular, building an MPI that uses the PSM library. If you use an MPI compiled for IB it will not take advantage of the PSM capabilities that are available in TrueScale and Omnipath.

**Comment by mwheinz** [comment]
That said, any verbs-based MPI should work with OmniPath it just won't get the full performance the fabric can provide.

**Comment by ddalessa** [comment]
Not updated in 8+ years. Not needed.
