### ISSUE TITLE
Broken postscripts in opafm package on systemd based systems

### ISSUE THREAD

**Issue by marbud0** [cornelisnetworks/opa-fm#26]
During the deployment of the newly built opafm package We noticed that the postinstall script in the package is trying to reload / restart the opafm service. It does this using the `service opafm restart` command. .Now, with systemd based systems, systemd will notice the change of the service file and ignore any action until a  `systemctl daemon-reload` action is preformed. Thus, the current post install scripts in the package is broken for systemd based systems (most modern systems..)

Noticed on the releases/tag/v10.11.2.0.3

**Comment by ddalessa** [comment]
What distro are you running as your base OS?

**Comment by marbud0** [comment]
Sles15.2

**Comment by ddalessa** [comment]
This should be working now. Sorry for not updating this ticket.
