### ISSUE TITLE
Please, use a standard build system

### ISSUE THREAD

**Issue by ana** [cornelisnetworks/opa-fm#6]
Hi,

The current build system of opa-fm seems to be some home made system with the only goal of generating a RPM package. The code also contains hard coded paths assuming the system uses `/etc/sysconfig` and that the installation target is `/opt`.

If you could switch to a more standard build system (Cmake, autotools, etc, your choice!), it would be easier for people to build and install opa-fm. Right now, it's very difficult to do a manual installation of opa-fm, or a  package, I had to patch heavily to remove all the hard coded paths to get a preliminary Debian package and it have seen the RedHat/Centos package also had to do some crude hacking.

Please, if you could use autotools like https://github.com/01org/psm  it would be great.

**Comment by ahkok** [comment]
3 years have passed and not a single comment was reported on this request, while obviously it is a critical flaw in the project.

**Comment by ddalessa** [comment]
README contains simplified instructions to build. Build is based on RHEL SRPM packaging. Closing as this is 8 years old.
