### ISSUE TITLE
May be some bugs in spoofing check in 10.4

### ISSUE THREAD

**Issue by onewayforever** [cornelisnetworks/opa-fm#8]
When using fabric_sim(10.4.0.0.86) to validation the 10.4 fm, it failed due to spoofing check
but fm v10.3 works fine with spoofing check

I disabled the spoofing check in config file to move on, but there may be some bugs to be fixed here

please have a check, thank you!

Wed Dec 28 10:28:49 2016: fm0_sm(30455): [main]: SM: Using: HFI 1 Port 1 PortGuid 0x0011750101670d4f
Wed Dec 28 10:28:51 2016: fm0_sm(30455): PROGR[topology]: SM: sm_transition: SM STATE TRANSITION from NOTACTIVE to DISCOVERING
Wed Dec 28 10:28:51 2016: fm0_sm(30455): PROGR[topology]: SM: topology_main: TT: DISCOVERY CYCLE START - REASON: Initial sweep.

Wed Dec 28 10:28:51 2016: fm0_sm(30455): PROGR[topology]: SM: sm_set_local_port_pkey: sm pkey table already set
Wed Dec 28 10:28:51 2016: fm0_sm(30455): ERROR[topology]: SM: sm_stl_quarantine_node: Neighbor of FI torus_node2 hfi1_0 NodeGUID 0x0011750101670d4f port 1 could not be authenticated. Reports: FI MOOSE_STL_SWITCH0 Guid 0x0002b30102000000 Port 25: Actual: HFI Guid 0x0011750101670d69, Port 1)
Wed Dec 28 10:28:51 2016: fm0_sm(30455): ERROR[topology]: SM: sm_stl_quarantine_node: Authentication expected from the neighbor guid 0x0011750101670d69 neighbor node type HFI
Wed Dec 28 10:28:51 2016: fm0_sm(30455): WARN [topology]: SM: topology_discovery:  unable to setup port[1] of node torus_node2 hfi1_0, nodeGuid 0x0011750101670d4f, ignoring port!
Wed Dec 28 10:28:51 2016: fm0_sm(30455): ERROR[topology]: SM: topology_discovery: SM neighbor is quarantined. Cannot manage fabric. Transitioning to NOTACTIVE.

**Comment by sjb017** [comment]
Hello,

Thank you for your inquiry. I will consult with the development team and get back to you.

Scott Breyer
Intel Corporation
Maintainer
01org/opa-fm

**Comment by mwheinz** [comment]
Scott, I suspect this is a known issue, the appliance check didn't work in 10.3.

Sent from my iPad

On Jan 11, 2017, at 5:17 PM, Scott J Breyer <notifications@github.com<mailto:notifications@github.com>> wrote:

Hello,

Thank you for your inquiry. I will consult with the development team and get back to you.

Scott Breyer
Intel Corporation
Maintainer
01org/opa-fm

**Comment by ddalessa** [comment]
This should be fixed the version used here is ancient. Please re-open if this is still a problem.
